export function AutoDealerJsonLd() {
  const jsonLd = {"@context":"https://schema.org","@type":"AutoDealer",name:"Speedway Motors LLC",url:"https://www.speedwaymotorsllc.com/",description:"Full service New Jersey used car dealer offering quality cars, SUVs, trucks, and vans with easy financing options.",telephone:"+1-862-264-2777",email:"info@speedwaymotorsllc.com",address:{"@type":"PostalAddress",streetAddress:"302-304 22nd Ave",addressLocality:"Paterson",addressRegion:"NJ",postalCode:"07513",addressCountry:"US"},geo:{"@type":"GeoCoordinates",latitude:"40.9168",longitude:"-74.1718"},openingHoursSpecification:[{"@type":"OpeningHoursSpecification",dayOfWeek:["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],opens:"09:30",closes:"19:00"},{"@type":"OpeningHoursSpecification",dayOfWeek:"Sunday",opens:"00:00",closes:"00:00"}],aggregateRating:{"@type":"AggregateRating",ratingValue:"4.8",reviewCount:"120",bestRating:"5"},areaServed:["Paterson","Totowa","Hawthorne","Fair Lawn","Clifton","Passaic","Garfield","Elmwood Park","Saddle Brook","Ridgewood","Glen Rock","Little Falls","Lodi","Cedar Grove"],priceRange:"$$",sameAs:["https://www.facebook.com/speedwaynj/"]};
  return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />;
}

export function FAQPageJsonLd() {
  const jsonLd = {"@context":"https://schema.org","@type":"FAQPage",mainEntity:[{"@type":"Question",name:"What financing options does Speedway Motors offer?",acceptedAnswer:{"@type":"Answer",text:"We work with most major banks and lending institutions in NJ to offer affordable financing. We also provide sub-prime financing — bad credit, no credit, or first-time buyers are all welcome."}},{"@type":"Question",name:"What brands does Speedway Motors carry?",acceptedAnswer:{"@type":"Answer",text:"We carry 20+ brands including Acura, Audi, BMW, Chevrolet, Dodge, Ford, Honda, Hyundai, INFINITI, Jeep, Land Rover, Mercedes-Benz, Nissan, Ram, Subaru, Toyota, Volkswagen, and Volvo."}},{"@type":"Question",name:"Where is Speedway Motors located?",acceptedAnswer:{"@type":"Answer",text:"Our main showroom is at 302-304 22nd Ave, Paterson, NJ 07513. We serve all of Passaic County and surrounding areas throughout New Jersey."}},{"@type":"Question",name:"Do you offer vehicle warranties?",acceptedAnswer:{"@type":"Answer",text:"Yes. Many of our vehicles are eligible for extended service contracts and warranties. Our team will walk you through available coverage options."}},{"@type":"Question",name:"Can I sell or trade in my car at Speedway Motors?",acceptedAnswer:{"@type":"Answer",text:"Absolutely. We offer competitive trade-in values and also purchase vehicles directly — no trade required. Submit your details for a quick offer."}}]};
  return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />;
}
