export interface GeoLocation {
  slug: string;
  city: string;
  state: string;
  stateAbbr: string;
  county?: string;
  displayName: string;
  distanceMiles: number;
  nearbyAreas: string[];
  targetKeywords: string[];
  intro: string;
  faqTopics: Array<"distance" | "financing" | "trade-in" | "test-drive" | "documents">;
  featuredMakes?: string[];
  coordinates?: { lat: number; lng: number };
}

export const geoLocations: GeoLocation[] = [
  {
    slug: "newark-nj",
    city: "Newark",
    state: "New Jersey",
    stateAbbr: "NJ",
    county: "Essex",
    displayName: "Newark, NJ",
    distanceMiles: 13,
    nearbyAreas: ["East Orange", "Irvington", "Harrison"],
    targetKeywords: [
      "used cars near Newark NJ",
      "used car dealership near Newark",
      "car financing Newark NJ",
      "buy used Honda near Newark NJ",
      "bad credit car loans Newark NJ",
      "used SUV near Newark New Jersey",
      "trade in car near Newark NJ",
      "car dealership near Newark no credit check",
      "used Toyota near Newark NJ",
      "affordable used cars Essex County NJ",
    ],
    intro:
      "Shopping from Newark should be straightforward. Speedway Motors gives Newark drivers a practical route to quality used vehicles, transparent pricing, and financing guidance without a high-pressure process.",
    faqTopics: ["distance", "financing", "trade-in", "test-drive", "documents"],
    featuredMakes: ["Honda", "Toyota", "Nissan"],
    coordinates: { lat: 40.7357, lng: -74.1724 },
  },
  {
    slug: "jersey-city-nj",
    city: "Jersey City",
    state: "New Jersey",
    stateAbbr: "NJ",
    county: "Hudson",
    displayName: "Jersey City, NJ",
    distanceMiles: 16,
    nearbyAreas: ["Journal Square", "The Heights", "Secaucus"],
    targetKeywords: [
      "used cars near Jersey City NJ",
      "used car financing near Jersey City",
      "trade in your car near Jersey City",
      "buy used Hyundai near Jersey City NJ",
      "used car dealer Hudson County NJ",
      "bad credit auto loan Jersey City NJ",
      "used Jeep near Jersey City New Jersey",
      "affordable SUV near Jersey City",
      "used Honda near Jersey City NJ",
      "no credit check car dealer near Jersey City NJ",
    ],
    intro:
      "If you are buying from Jersey City, our team helps you compare reliable options quickly and handle financing in one place. Many shoppers come in with a short list and leave with a vehicle that fits both commute and budget.",
    faqTopics: ["distance", "financing", "test-drive", "trade-in"],
    featuredMakes: ["Hyundai", "Honda", "Jeep"],
    coordinates: { lat: 40.7178, lng: -74.0431 },
  },
  {
    slug: "paterson-nj",
    city: "Paterson",
    state: "New Jersey",
    stateAbbr: "NJ",
    county: "Passaic",
    displayName: "Paterson, NJ",
    distanceMiles: 0,
    nearbyAreas: ["Haledon", "Prospect Park", "Totowa"],
    targetKeywords: [
      "used cars in Paterson NJ",
      "Paterson used car dealership",
      "auto financing Paterson NJ",
      "buy used Ford near Paterson NJ",
      "used trucks Paterson New Jersey",
      "bad credit car dealer Paterson NJ",
      "used Toyota Paterson NJ",
      "trade in car Paterson NJ",
      "used SUV Paterson New Jersey",
      "car lots on 22nd Ave Paterson NJ",
    ],
    intro:
      "Paterson drivers are local to our main showroom on 22nd Ave. You can browse inventory in person, review financing options, and get trade-in guidance from one team in a single visit.",
    faqTopics: ["distance", "financing", "trade-in", "test-drive", "documents"],
    featuredMakes: ["Ford", "Toyota", "Chevrolet"],
    coordinates: { lat: 40.9168, lng: -74.1718 },
  },
  {
    slug: "yonkers-ny",
    city: "Yonkers",
    state: "New York",
    stateAbbr: "NY",
    county: "Westchester",
    displayName: "Yonkers, NY",
    distanceMiles: 21,
    nearbyAreas: ["Getty Square", "Northwest Yonkers", "Hastings-on-Hudson"],
    targetKeywords: [
      "used cars near Yonkers NY",
      "trade in your car near Yonkers",
      "used car financing near Yonkers",
      "buy used BMW near Yonkers NY",
      "used Mercedes-Benz near Yonkers New York",
      "bad credit auto loan near Yonkers NY",
      "used luxury cars Westchester County NY",
      "used Audi near Yonkers NY",
      "car dealer near Yonkers NY NJ border",
      "affordable luxury used cars near Yonkers",
    ],
    intro:
      "Yonkers customers looking outside city inventory often visit Speedway for broader selection and a transparent buying process. We keep financing and trade-in steps clear so your trip is productive.",
    faqTopics: ["distance", "financing", "trade-in", "test-drive"],
    featuredMakes: ["BMW", "Mercedes-Benz", "Audi"],
    coordinates: { lat: 40.9312, lng: -73.8988 },
  },
  {
    slug: "hoboken-nj",
    city: "Hoboken",
    state: "New Jersey",
    stateAbbr: "NJ",
    county: "Hudson",
    displayName: "Hoboken, NJ",
    distanceMiles: 14,
    nearbyAreas: ["Downtown Hoboken", "Uptown Hoboken", "Weehawken"],
    targetKeywords: [
      "used cars near Hoboken NJ",
      "used SUV near Hoboken",
      "auto financing near Hoboken",
      "buy used Mazda near Hoboken NJ",
      "used Subaru near Hoboken New Jersey",
      "car dealer near Hoboken no pressure",
      "trade in car near Hoboken NJ",
      "used Toyota near Hoboken NJ",
      "affordable used car dealer Hudson County NJ",
      "bad credit financing near Hoboken NJ",
    ],
    intro:
      "Hoboken shoppers who need a dependable used car with practical financing terms can shop with Speedway online first, then visit Paterson to test drive and finalize details.",
    faqTopics: ["distance", "financing", "test-drive", "documents"],
    featuredMakes: ["Mazda", "Subaru", "Toyota"],
    coordinates: { lat: 40.743, lng: -74.0324 },
  },
  {
    slug: "clifton-nj",
    city: "Clifton",
    state: "New Jersey",
    stateAbbr: "NJ",
    county: "Passaic",
    displayName: "Clifton, NJ",
    distanceMiles: 4,
    nearbyAreas: ["Athenia", "Allwood", "Montclair Heights"],
    targetKeywords: [
      "used cars near Clifton NJ",
      "car financing Clifton NJ",
      "buy used Nissan near Clifton NJ",
      "used Honda near Clifton New Jersey",
      "car dealer 5 minutes from Clifton NJ",
      "bad credit auto loan Clifton NJ",
      "trade in car near Clifton NJ",
      "used Kia near Clifton NJ",
      "used sedans and SUVs near Clifton",
      "Passaic County used car dealer near Clifton",
    ],
    intro:
      "From Clifton, Speedway is a short drive for drivers who want quick access to used sedans, SUVs, and trucks with clear monthly payment options.",
    faqTopics: ["distance", "financing", "trade-in", "test-drive"],
    featuredMakes: ["Nissan", "Honda", "Kia"],
    coordinates: { lat: 40.8584, lng: -74.1638 },
  },
  {
    slug: "passaic-nj",
    city: "Passaic",
    state: "New Jersey",
    stateAbbr: "NJ",
    county: "Passaic",
    displayName: "Passaic, NJ",
    distanceMiles: 3,
    nearbyAreas: ["Passaic Park", "Wallington", "Garfield"],
    targetKeywords: [
      "used cars near Passaic NJ",
      "trade-in near Passaic",
      "buy used Honda near Passaic NJ",
      "used Hyundai near Passaic New Jersey",
      "bad credit car dealer near Passaic NJ",
      "auto financing Passaic County NJ",
      "used Ford near Passaic NJ",
      "car dealer minutes from Passaic NJ",
      "used SUV near Passaic New Jersey",
      "sub-prime auto loan near Passaic NJ",
    ],
    intro:
      "Passaic buyers choose Speedway for straightforward pricing, varied inventory, and support for both strong-credit and credit-rebuilding financing applications.",
    faqTopics: ["distance", "financing", "trade-in", "documents"],
    featuredMakes: ["Honda", "Hyundai", "Ford"],
    coordinates: { lat: 40.8568, lng: -74.1285 },
  },
  // ── New high-demand markets ─────────────────────────────────────────────────
  {
    slug: "hackensack-nj",
    city: "Hackensack",
    state: "New Jersey",
    stateAbbr: "NJ",
    county: "Bergen",
    displayName: "Hackensack, NJ",
    distanceMiles: 12,
    nearbyAreas: ["South Hackensack", "Teaneck", "Maywood"],
    targetKeywords: [
      "used cars near Hackensack NJ",
      "used car dealer Bergen County NJ",
      "car financing Hackensack NJ",
      "buy used Toyota near Hackensack",
      "used Honda near Hackensack NJ",
      "bad credit auto loan Bergen County NJ",
      "trade in car near Hackensack NJ",
      "used SUV near Hackensack New Jersey",
      "affordable used car dealer near Hackensack",
      "no credit check financing near Hackensack NJ",
    ],
    intro:
      "Hackensack drivers looking for a wider selection and straightforward financing can reach Speedway Motors in under 20 minutes. We carry 180+ vehicles across every body type and price range.",
    faqTopics: ["distance", "financing", "trade-in", "test-drive"],
    featuredMakes: ["Toyota", "Honda", "Chevrolet"],
    coordinates: { lat: 40.8859, lng: -74.0435 },
  },
  {
    slug: "elizabeth-nj",
    city: "Elizabeth",
    state: "New Jersey",
    stateAbbr: "NJ",
    county: "Union",
    displayName: "Elizabeth, NJ",
    distanceMiles: 18,
    nearbyAreas: ["Elizabethport", "Elmora", "Linden"],
    targetKeywords: [
      "used cars near Elizabeth NJ",
      "used car dealer Union County NJ",
      "auto financing Elizabeth NJ",
      "buy used Nissan near Elizabeth NJ",
      "bad credit car loans Elizabeth NJ",
      "used Toyota near Elizabeth New Jersey",
      "trade in car near Elizabeth NJ",
      "used Honda near Elizabeth NJ",
      "used trucks near Elizabeth New Jersey",
      "sub-prime car dealer near Elizabeth NJ",
    ],
    intro:
      "Elizabeth drivers shopping for quality used vehicles can browse Speedway's full inventory online before making the trip to Paterson. Our team handles financing and trade-ins in one visit.",
    faqTopics: ["distance", "financing", "trade-in", "test-drive", "documents"],
    featuredMakes: ["Nissan", "Toyota", "Honda"],
    coordinates: { lat: 40.6640, lng: -74.2107 },
  },
  {
    slug: "union-city-nj",
    city: "Union City",
    state: "New Jersey",
    stateAbbr: "NJ",
    county: "Hudson",
    displayName: "Union City, NJ",
    distanceMiles: 15,
    nearbyAreas: ["West New York", "North Bergen", "Guttenberg"],
    targetKeywords: [
      "used cars near Union City NJ",
      "car dealer near Union City NJ",
      "auto financing Union City NJ",
      "buy used Honda near Union City",
      "bad credit car loan Union City NJ",
      "used Hyundai near Union City New Jersey",
      "trade in car near Union City NJ",
      "used SUV near Union City NJ",
      "affordable used cars Hudson County NJ",
      "first time car buyer near Union City NJ",
    ],
    intro:
      "Union City residents can shop Speedway's full inventory from home and visit for a test drive and financing approval in one trip. We welcome first-time buyers and those rebuilding credit.",
    faqTopics: ["distance", "financing", "trade-in", "test-drive"],
    featuredMakes: ["Honda", "Hyundai", "Kia"],
    coordinates: { lat: 40.7673, lng: -74.0268 },
  },
  {
    slug: "bloomfield-nj",
    city: "Bloomfield",
    state: "New Jersey",
    stateAbbr: "NJ",
    county: "Essex",
    displayName: "Bloomfield, NJ",
    distanceMiles: 10,
    nearbyAreas: ["Glen Ridge", "Montclair", "Nutley"],
    targetKeywords: [
      "used cars near Bloomfield NJ",
      "car dealership near Bloomfield New Jersey",
      "auto financing Bloomfield NJ",
      "buy used Toyota near Bloomfield",
      "used Subaru near Bloomfield NJ",
      "trade in car near Bloomfield NJ",
      "bad credit auto loan near Bloomfield NJ",
      "used SUV near Bloomfield Essex County",
      "used sedan near Bloomfield NJ",
      "affordable used cars near Montclair NJ",
    ],
    intro:
      "Bloomfield shoppers benefit from Speedway's proximity — just 10 miles to our Paterson showroom — with an inventory that covers sedans, SUVs, trucks, and commercial vehicles at competitive prices.",
    faqTopics: ["distance", "financing", "trade-in", "test-drive"],
    featuredMakes: ["Toyota", "Subaru", "Honda"],
    coordinates: { lat: 40.8068, lng: -74.1854 },
  },
  {
    slug: "bronx-ny",
    city: "Bronx",
    state: "New York",
    stateAbbr: "NY",
    county: "Bronx",
    displayName: "The Bronx, NY",
    distanceMiles: 25,
    nearbyAreas: ["Yonkers", "Mount Vernon", "New Rochelle"],
    targetKeywords: [
      "used cars near the Bronx NY",
      "car dealer near Bronx New York",
      "auto financing Bronx NY",
      "buy used car near Bronx no credit check",
      "bad credit car loan Bronx NY",
      "used SUV near Bronx New York",
      "trade in car near Bronx NY",
      "used Honda near the Bronx NY",
      "affordable used car dealer near Bronx",
      "used trucks near Bronx New York",
    ],
    intro:
      "Bronx drivers looking for a larger inventory and competitive financing often cross into New Jersey. Speedway Motors is about 25 miles from the Bronx with 180+ vehicles and flexible credit options.",
    faqTopics: ["distance", "financing", "trade-in", "test-drive", "documents"],
    featuredMakes: ["Honda", "Toyota", "Chevrolet"],
    coordinates: { lat: 40.8448, lng: -73.8648 },
  },
];

export const geoLocationBySlug = new Map(geoLocations.map((location) => [location.slug, location]));
